language: go

go_import_path: github.com/schlund/go-acc

go:
  - 1.8

env:
  - GO15VENDOREXPERIMENT=1

install:
   - go get ./...

script:
  - go install .
  - go-acc github.com/schlund/go-acc
  - go-acc github.com/schlund/go-acc/...
  - go-acc $(go list github.com/schlund/go-acc/...)
